/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secure;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import static secure.usrdatabase.date;
import static secure.usrdatabase.usr;

/**
 *
 * @author Himanshi-pc
 */
public class anyday extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
PreparedStatement pst1=null;
PreparedStatement pst2=null;
ResultSet rs=null;
ResultSet rs1=null;
ResultSet rs2=null;
public static String usr,date;
    /**
     * Creates new form anyday
     */
    public anyday() {
        initComponents();
        
    }
    public anyday(String user)
    {
       
        usr=user;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Constantia", 2, 36)); // NOI18N
        jLabel1.setText("MAXIMUM LIMIT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(660, 150, 430, 70);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(640, 20, 217, 48);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Entity Name", "Amount Spendid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(1060, 340, 540, 540);

        jLabel4.setText("TOTAL VALUE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(470, 890, 270, 40);

        jLabel6.setText("TOTAL VALUE");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1360, 890, 260, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Source of Income", "Amount Recieved"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Source of Income");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Amount Recieved");
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 340, 520, 540);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("TOTAL");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 890, 160, 44);

        jButton1.setFont(new java.awt.Font("Lucida Bright", 3, 36)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(950, 30, 160, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setText("TOTAL");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1160, 890, 170, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("INCOME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 270, 220, 70);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel8.setText("EXPENSE");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1220, 270, 260, 70);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1010, 160, 230, 40);

        jButton2.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 0, 120, 37);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calcbudget.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, -20, 2000, 1120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        
        conn=Connect.Connect();
        String date=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String sql="select * from LOG."+usr+" where date='"+date+"'";
        try{
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
         DefaultTableModel model,model1;
        model=(DefaultTableModel)this.jTable1.getModel();
        model1=(DefaultTableModel)this.jTable2.getModel();
        while(model.getRowCount()>0)
        {
            for(int i=0;i<model.getRowCount();i++)
            {
                model.removeRow(i);
            }
        }
        while(model1.getRowCount()>0)
        {
            for(int i=0;i<model.getRowCount();i++)
            {
                model1.removeRow(i);
            }
        }
            while(rs.next())
            {
            jLabel9.setText(Integer.toString(rs.getInt("limit")));
            String enm=rs.getString("ename");
            int eamt=rs.getInt("eamnt");
            model.addRow(new Object[]{enm,eamt});
            String inm=rs.getString("iname");
            int iamt=rs.getInt("iamnt");
            model1.addRow(new Object[]{inm,iamt});
            }
            String sql1="select sum(eamnt) from "+usr+" where date='"+date+"'";
         pst1=conn.prepareStatement(sql1);
         rs1=pst1.executeQuery();
          int sum=0;
          
         if(rs1.next())
         {
           sum=rs1.getInt(1);
         }
          String tot=Integer.toString(sum);
            jLabel4.setText(tot);
            String sql2="select sum(iamnt) from "+usr+" where date='"+date+"'";
         pst1=conn.prepareStatement(sql2);
         rs1=pst1.executeQuery();
          int sum1=0;
          
         if(rs1.next())
         {
           sum1=rs1.getInt(1);
         }
          String tot1=Integer.toString(sum1);
            jLabel6.setText(tot1);
           jLabel9.setFont(new Font("Serif",Font.PLAIN,30));
           jLabel4.setFont(new Font("Serif",Font.PLAIN,50));
           jLabel6.setFont(new Font("Serif",Font.PLAIN,50));
           jTable1.setFont(new Font("Seriff",Font.PLAIN,20));
           jTable1.setRowHeight(30);
           jTable2.setFont(new Font("Seriff",Font.PLAIN,20));
           jTable2.setRowHeight(30);
        }
        catch(Exception e)
        {
            
        }
        SwingUtilities.updateComponentTreeUI(getContentPane());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.hide();
        budget b=new budget();
        b.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anyday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anyday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anyday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anyday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anyday().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
