package secure;
import java.sql.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import javax.swing.*;

//import secure.resetpswd;
//import secure.signup;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 141229
 */
public class login extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form login
     */
    
    Timer tm;
    int x=0;
    String[] list={  "C:\\Users\\Himanshi-pc\\Desktop\\Budget_Tracker\\src\\image\\how-to-budget-expenses-1-1024x614.jpg",
        "C:\\Users\\Himanshi-pc\\Desktop\\Budget_Tracker\\src\\image\\Budget-of-punjab-2013-2014.jpg",
        "C:\\Users\\Himanshi-pc\\Desktop\\Budget_Tracker\\src\\image\\bigstock-Income-Expenses-Files-Show-Bud-36328051.jpg",
        "C:\\Users\\Himanshi-pc\\Desktop\\Budget_Tracker\\src\\image\\income-expenditure-ppt-1-728.jpg",
        "C:\\Users\\Himanshi-pc\\Desktop\\Budget_Tracker\\src\\image\\13206736-Red-block-letters-of-words-budget-incomes-and-expenses-isolated-on-white-Budgeting-Stock-Photo.jpg"
 };
    public login() {
         //super("Java Slideshow");
        initComponents();
        setTitle("LOGIN");
        getContentPane().setBackground(new Color(204,244,255));
        
        pic.setBounds(40,30,860,1080);
        SetImageSize(0);
        
        tm= new Timer(1000,new ActionListener(){
        
        
        public void actionPerformed(ActionEvent e) {
            SetImageSize(x);
            x+=1;
            if(x>=list.length)
                x=0;
       

        }
        });
        add(pic);
        tm.start();
        
        setVisible(true);
    }
    public void SetImageSize(int i)
    {
        //ImageIcon II=new ImageIcon(getClass().getResource("/image/calcbudget.png"));
        ImageIcon icon=new ImageIcon(list[i]);
        Image img=icon.getImage();
        Image newImg=img.getScaledInstance(pic.getWidth(), pic.getHeight(),Image.SCALE_SMOOTH );
        ImageIcon newImc= new ImageIcon(newImg);
        pic.setIcon(newImc);
        //jLabel1.setIcon(II);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Usrname_Txt = new javax.swing.JTextField();
        Pass = new javax.swing.JLabel();
        Pass_Txt = new javax.swing.JPasswordField();
        SignUp = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(610, 521));
        jPanel1.setLayout(null);

        jPanel3.setMinimumSize(new java.awt.Dimension(860, 1080));
        jPanel3.setPreferredSize(new java.awt.Dimension(860, 1080));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(120, 0, 860, 1080);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(990, 40, 650, 210);

        Username.setFont(new java.awt.Font("Sitka Small", 3, 36)); // NOI18N
        Username.setText("USER NAME");
        jPanel1.add(Username);
        Username.setBounds(1030, 390, 270, 60);

        Usrname_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usrname_TxtActionPerformed(evt);
            }
        });
        jPanel1.add(Usrname_Txt);
        Usrname_Txt.setBounds(1310, 390, 260, 50);

        Pass.setFont(new java.awt.Font("Sitka Small", 3, 36)); // NOI18N
        Pass.setText("PASSWORD");
        jPanel1.add(Pass);
        Pass.setBounds(1030, 510, 230, 50);
        jPanel1.add(Pass_Txt);
        Pass_Txt.setBounds(1310, 510, 260, 50);

        SignUp.setFont(new java.awt.Font("Lucida Bright", 3, 36)); // NOI18N
        SignUp.setText("SIGN UP");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        jPanel1.add(SignUp);
        SignUp.setBounds(1050, 660, 200, 60);

        Login.setFont(new java.awt.Font("Lucida Bright", 3, 36)); // NOI18N
        Login.setText("LOGIN");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login);
        Login.setBounds(1310, 660, 210, 60);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1350, 760, 210, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Small-Man-Contact-Us.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1440, 170, 480, 940);

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(1938, 1127));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        try{
            conn=Connect.Connect();
            String sql="select * from LOG.SIGNIN where username=? and pswd=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,Usrname_Txt.getText());
            pst.setString(2,Pass_Txt.getText());
                             
            rs=pst.executeQuery();
            if(rs.next())
            {
               this.hide();
               usrdatabase u=new usrdatabase();
               usrdatabase u1=new usrdatabase(Usrname_Txt.getText());
              
                u.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid username or password");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        //TODO add your handling code here:
         this.hide();
       signup s=new signup();
       s.setVisible(true);
    }//GEN-LAST:event_SignUpActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.hide();
       forgotpswd_usrname f=new forgotpswd_usrname();
       f.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void Usrname_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usrname_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usrname_TxtActionPerformed
public void close()
{
    WindowEvent winclose =new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JLabel Pass;
    private javax.swing.JPasswordField Pass_Txt;
    private javax.swing.JButton SignUp;
    private javax.swing.JLabel Username;
    public static javax.swing.JTextField Usrname_Txt;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel pic;
    // End of variables declaration//GEN-END:variables
}
