package secure;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Himanshi-pc
 */

import java.awt.*;
import java.sql.*;
import javax.swing.JOptionPane;

public class resetpswd extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;

   
    /**
     * Creates new form forgot_pswd
     */
     public static String usr;
    public resetpswd() {
        initComponents();
        setTitle("RESET PASSWORD");
        getContentPane().setBackground(new Color(204,244,255));
        jLabel6.setFont(new Font("Serif",Font.PLAIN,30));
    }
     public resetpswd(String usr1) {
         initComponents();
         usr = usr1;
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SecAns_Txt = new javax.swing.JTextField();
        CnfrmPass_Txt = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        NewPass_Txt = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(820, 280, 580, 40);

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Constantia", 3, 76)); // NOI18N
        jLabel1.setText("RESET PASSWORD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(560, 130, 730, 90);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel3.setText("Security Answer");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 350, 250, 70);

        jButton3.setFont(new java.awt.Font("Lucida Bright", 3, 36)); // NOI18N
        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(960, 630, 200, 60);

        jButton1.setFont(new java.awt.Font("Lucida Bright", 3, 36)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 630, 190, 60);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setText("New Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(490, 420, 250, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("Security Question");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 270, 280, 60);
        jPanel1.add(SecAns_Txt);
        SecAns_Txt.setBounds(820, 360, 267, 40);
        jPanel1.add(CnfrmPass_Txt);
        CnfrmPass_Txt.setBounds(820, 510, 267, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel5.setText("Confirm Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 510, 300, 50);

        jButton2.setFont(new java.awt.Font("Lucida Bright", 3, 36)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(720, 630, 190, 60);
        jPanel1.add(NewPass_Txt);
        NewPass_Txt.setBounds(820, 430, 267, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calcbudget.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, -110, 1920, 1290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1938, 1127));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.hide();
        login l=new login();
        l.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        CnfrmPass_Txt.setText("");
        NewPass_Txt.setText("");
        SecAns_Txt.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            conn=Connect.Connect();
            String newpswd=NewPass_Txt.getText();
            String cnfrmpswd=CnfrmPass_Txt.getText();
            String sql2="select * from LOG.SIGNIN where username='"+usr+"'";
            pst=conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            String validate = null;
            if(rs.next())
            {
                 validate=rs.getString("secans");
            }
            if(SecAns_Txt.getText().equals(validate))
            {
            if(newpswd.equals(cnfrmpswd))
            {
            Statement stmt=conn.createStatement();
            String sql="update LOG.SIGNIN set PSWD='"+newpswd+"' where USERNAME='"+usr+"'";
            stmt.executeUpdate(sql);
             JOptionPane.showMessageDialog(null, "Password is successfully updated");
             this.hide();
            login l=new login();
            l.setVisible(true);
            }
            else
            {
              JOptionPane.showMessageDialog(null, "Reconfirm Password");
            }
            }
            else
            {
            JOptionPane.showMessageDialog(null, "Wrongly Entered Security Answer!!");
            }
    }//GEN-LAST:event_jButton1ActionPerformed
    catch(Exception e)
   {
       JOptionPane.showMessageDialog(null, e);
   }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetpswd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetpswd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetpswd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetpswd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetpswd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CnfrmPass_Txt;
    private javax.swing.JPasswordField NewPass_Txt;
    private javax.swing.JTextField SecAns_Txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
