/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secure;

import com.sun.glass.events.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
//import static com.sun.javafx.tk.Toolkit.getToolkit;
import java.sql.Connection;
import com.sun.media.sound.*;
//import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;

import java.util.Date;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
//import java.util.*;
//import javax.swing.JTextField;

/**
 *
 * @author Himanshi-pc
 */
public class usrdatabase extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
PreparedStatement pst1=null;
PreparedStatement pst2=null,pst3=null;
ResultSet rs=null;
ResultSet rs1=null;
ResultSet rs2=null;
    /**
     * Creates new form usrdatabase
     */
    public static String usr,date,t;
    public static int l;
    public usrdatabase() {
        initComponents();
        conn=Connect.Connect();
        usr=login.Usrname_Txt.getText();
        Date d=new Date();
      SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd");
      date=s.format(d);
     // DateFormat df = new SimpleDateFormat("HH:mm:ss");
     // Calendar calobj = Calendar.getInstance();
     //t=df.format(calobj.getTime());
      
      try{
         String sql2="select limit from "+usr+" where date='"+date+"'";
       pst2=conn.prepareStatement(sql2);
         rs2=pst2.executeQuery();
         
         if(rs2.next())
         {
              l=rs2.getInt("limit");
         }
         if(l!=0)
         {
             limit_txt.hide();
             jLabel1.hide();
         }
        
       }catch(Exception e)
       {
           
       }
    }
public usrdatabase(String usr1) {
        initComponents();
       usr=usr1;
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        limit_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        iname_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        iamt_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ename_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        eamt_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jButton4.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        jButton4.setText("SIGNOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(1760, 0, 160, 40);

        jButton6.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        jButton6.setText("CLEAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(900, 780, 270, 50);

        jButton7.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        jButton7.setText("EDIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(1210, 780, 270, 50);

        jButton8.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        jButton8.setText("SAVE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(280, 780, 270, 50);

        jButton9.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        jButton9.setText("CHECK BUDGET");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(590, 780, 270, 50);

        limit_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                limit_txtKeyTyped(evt);
            }
        });
        jPanel2.add(limit_txt);
        limit_txt.setBounds(800, 170, 250, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setText("Maximum Limit Of Spending");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(470, 180, 300, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setText("Entity Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(640, 280, 172, 40);

        iname_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                iname_txtKeyTyped(evt);
            }
        });
        jPanel2.add(iname_txt);
        iname_txt.setBounds(800, 280, 250, 42);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel3.setText("Amount Received");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(590, 360, 200, 40);

        iamt_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iamt_txtActionPerformed(evt);
            }
        });
        iamt_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                iamt_txtKeyTyped(evt);
            }
        });
        jPanel2.add(iamt_txt);
        iamt_txt.setBounds(800, 360, 250, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel4.setText("Entity Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(660, 500, 162, 28);

        ename_txt.setToolTipText("");
        ename_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ename_txtKeyTyped(evt);
            }
        });
        jPanel2.add(ename_txt);
        ename_txt.setBounds(810, 490, 250, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel5.setText("Amount Spendid");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(600, 570, 201, 40);

        eamt_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                eamt_txtKeyTyped(evt);
            }
        });
        jPanel2.add(eamt_txt);
        eamt_txt.setBounds(810, 570, 250, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("EXPENSE ENTRY");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(730, 440, 170, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("INCOME ENTRY");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(730, 250, 170, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calcbudget.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, -110, 2040, 1300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1938, 1127));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.hide();
        login log=new login();
        log.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
         if(l==0)     
        {
            
            String sql="insert into "+usr+"(LIMIT,INAME,iamnt,ename,eamnt) values(?,?,?,?,?)";
            if(iname_txt.getText().equals("")||iamt_txt.getText().equals("")||ename_txt.getText().equals("")||eamt_txt.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Entry Fields Cannot Be Empty!");
            }
            else
            {
            try{
            pst=conn.prepareStatement(sql);
            pst.setInt(1,Integer.parseInt(limit_txt.getText()));
            pst.setString(2,iname_txt.getText());
            pst.setInt(3,Integer.parseInt(iamt_txt.getText()));
            pst.setString(4,ename_txt.getText());
            pst.setInt(5,Integer.parseInt(eamt_txt.getText()));
            pst.execute();

        String sql1="select sum(eamnt) from "+usr+" where date='"+date+"'";
         pst1=conn.prepareStatement(sql1);
         rs1=pst1.executeQuery();
          int sum=0;
          
         if(rs1.next())
         {
           sum=rs1.getInt(1);
         }
         if(sum>(Integer.parseInt(limit_txt.getText())))
         {
             InputStream in;
             in=new FileInputStream(new File("C:\\Users\\Himanshi-pc\\Desktop\\jar\\voice.wav"));
             AudioStream audios=new AudioStream(in);
             AudioPlayer.player.start(audios);
         }
         String sql5="insert into "+usr+"(etot) values(?)";
            pst1=conn.prepareStatement(sql5);
         pst1.setInt(1,sum);
          pst1.execute();
          String sql7="select sum(iamnt) from "+usr+" where date='"+date+"'";
         pst1=conn.prepareStatement(sql7);
         rs1=pst1.executeQuery();
         int sum2=0;
         if(rs1.next())
         {
           sum2=rs1.getInt(1);
         }
         String sql6="insert into "+usr+"(itot) values(?)";
            pst1=conn.prepareStatement(sql6);
         pst1.setInt(1,sum2);
          pst1.execute();
            }catch(Exception e)
            {
                
            }
             JOptionPane.showMessageDialog(null, "Saved");
            
            }
      
    
        limit_txt.setText("");
        iname_txt.setText("");
        iamt_txt.setText("");
        ename_txt.setText("");
        eamt_txt.setText("");
        try{
         String sql2="select limit from "+usr+" where date='"+date+"'";
       pst2=conn.prepareStatement(sql2);
         rs2=pst2.executeQuery();
         int l=0;
         if(rs2.next())
         {
              l=rs2.getInt("limit");
         }
         if(l!=0)
         {
             limit_txt.hide();
             jLabel1.hide();
         }
         
         //SwingUtilities.updateComponentTreeUI(getContentPane());
         //getContentPane().invalidate();
         //getContentPane().validate();
         getContentPane().repaint();
       }catch(Exception e)
       {
           
       }
     }
         else{
             //SwingUtilities.updateComponentTreeUI(getContentPane());
         if(l!=0)
         {
            
            
           if(iname_txt.getText().equals("")||iamt_txt.getText().equals("")||ename_txt.getText().equals("")||eamt_txt.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Entry Fields Cannot Be Empty!");
            }
                  else{
            try{
            String sql="insert into "+usr+"(LIMIT,INAME,iamnt,ename,eamnt) values(?,?,?,?,?)";    
            pst=conn.prepareStatement(sql);
            pst.setInt(1,l);
            pst.setString(2,iname_txt.getText());
            pst.setInt(3,Integer.parseInt(iamt_txt.getText()));
            pst.setString(4,ename_txt.getText());
            pst.setInt(5,Integer.parseInt(eamt_txt.getText()));
            pst.execute();
            String sql1="select sum(eamnt) from "+usr+" where date='"+date+"'";
            pst1=conn.prepareStatement(sql1);
            rs1=pst1.executeQuery();
            int sum=0;
            if(rs1.next())
            {
                sum=rs1.getInt(1);
            }
            if(sum>l)
            {
                 InputStream in;
                in=new FileInputStream(new File("C:\\Users\\Himanshi-pc\\Desktop\\jar\\voice.wav"));
                 AudioStream audios=new AudioStream(in);
                 AudioPlayer.player.start(audios);
            }
           
        String sql6="update "+usr+" set etot="+sum+" where date='"+date+"'";
       
         pst3=conn.prepareStatement(sql6);
         pst3.execute();
         String sql7="select sum(iamnt) from "+usr+" where date='"+date+"'";
         pst1=conn.prepareStatement(sql7);
         rs1=pst1.executeQuery();
         int sum2=0;
         if(rs1.next())
         {
           sum2=rs1.getInt(1);
         }
         String sql8="update "+usr+" set itot="+sum2+" where date='"+date+"'";
       
         pst3=conn.prepareStatement(sql8);
         pst3.execute();
            }catch(Exception e)
            {
                System.out.println(e);
            }
             JOptionPane.showMessageDialog(null, "Saved");
           
                  }
      
    
        limit_txt.setText("");
        iname_txt.setText("");
        iamt_txt.setText("");
        ename_txt.setText("");
        eamt_txt.setText("");
                 
                 
             
             
         }
         }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
               this.hide();
               budget b=new budget();
               budget b1=new budget(usr);
               b.setVisible(true);
               anyday a=new anyday(usr);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        limit_txt.setText("");
        iname_txt.setText("");
        iamt_txt.setText("");
        ename_txt.setText("");
        eamt_txt.setText("");
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void iamt_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iamt_txtKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Please enter a valid amount!");
            evt.consume();
        }
    }//GEN-LAST:event_iamt_txtKeyTyped

    private void eamt_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eamt_txtKeyTyped
      char c=evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Please enter valid amount!");
            evt.consume();
        }
    }//GEN-LAST:event_eamt_txtKeyTyped

    private void iamt_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iamt_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iamt_txtActionPerformed

    private void iname_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iname_txtKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)|| (c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Please enter valid name!");
            evt.consume();
        }
    }//GEN-LAST:event_iname_txtKeyTyped

    private void ename_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ename_txtKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)|| (c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Please enter valid name!");
            evt.consume();
        }
    }//GEN-LAST:event_ename_txtKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

               this.hide();
               edit_budget e=new edit_budget();
               e.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void limit_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_limit_txtKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Please enter valid limit !");
            evt.consume();
        }
    }//GEN-LAST:event_limit_txtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usrdatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usrdatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usrdatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usrdatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usrdatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eamt_txt;
    private javax.swing.JTextField ename_txt;
    private javax.swing.JTextField iamt_txt;
    private javax.swing.JTextField iname_txt;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField limit_txt;
    // End of variables declaration//GEN-END:variables
}
